### ISSUE TITLE
InvalidProgramException:  locals size too big

### ISSUE THREAD

**Issue by ppereira-serviceonsites** [angularsen/UnitsNet#1016]
> I am trying to use the UnitsNet library in my .NET 6 Blazor WebAssembly project.  Included it through Nuget package V4.113.0
 
It works great except for the UnitConverter.  Whenever I try one of the examples:
        double d1 = UnitConverter.Convert(1, LengthUnit.Centimeter, LengthUnit.Millimeter); // 10 mm
        double d2 = UnitConverter.ConvertByName(1, "Length", "Centimeter", "Millimeter"); // 10 mm
        double d3 = UnitConverter.ConvertByAbbreviation(1, "Length", "cm", "mm"); // 10 mm
 
I get the following error:
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The type initializer for 'UnitsNet.UnitConverter' threw an exception.
System.TypeInitializationException: The type initializer for 'UnitsNet.UnitConverter' threw an exception.
---> System.InvalidProgramException: Unable to run method 'void UnitsNet.UnitConverter:RegisterDefaultConversions (UnitsNet.UnitConverter)': locals size too big.
   at UnitsNet.UnitConverter..cctor()
   --- End of inner exception stack trace ---

Has anyone else had this issue?

**Comment by angularsen** [comment]
I have no experience with Units.NET in Blazor WebAssembly, but my hunch is that either AOT strips it out, or webassembly stumbles on our large number of types and methods/properties in the library. IL2CPP in Unity3D apparently had similar issues.

https://github.com/angularsen/UnitsNet/issues/1009

Since it seems to crash on UnitConverter ctor, which is default, I suspect it is really having trouble with the static ctor:
https://github.com/angularsen/UnitsNet/blob/master/UnitsNet/UnitConverter.cs#L45-L49

We load tons of things there. Maybe it is too slow? Maybe it uses too much memory?

The only relevant hit on Google was this, which seems to deal with large arrays. We have large dictionaries. Nothing crazy large, but definitely large.
https://github.com/dotnet/runtime/issues/46622

**Comment by angularsen** [comment]
If you are able to debug with source code, it would be helpful to try to comment out the static ctor or reduce the amount of data it loads to see if it helps.

**Comment by tmilnthorp** [comment]
The only thing I can think of is just the sheer size of this method. I created PR #1018 to see if this would help. Unfortunately I have no way to test if this fixes it or not, so please give it a go.
