### ISSUE TITLE
Add Deca prefix for Liter

### ISSUE THREAD

**Issue by JasLieb** [angularsen/UnitsNet#1033]
**Is your feature request related to a problem? Please describe.**
I want to use Decaliter unit but isn't available yet. 
For example, I have to convert decaliter to liter or another else volume unit

**Describe the solution you'd like**
Add Decaliter enum value in available VolumeUnit

Sorry in advance for my bad English or my misunterstanding of the code of conduct or bad issue writing.

**Comment by angularsen** [comment]
Nuget on the way.

[Release UnitsNet/4.119.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F4.119.0)

**Comment by JasLieb** [comment]
Thanks for your fast issue resolving, it works like a charm ! 
I didn't check all prefix in JSON models but I'm thinking (because this current issue and the #1034) maybe there is some units which are missing _Deca_ prefix ?

**Comment by angularsen** [comment]
I'm sure more are missing, but generally I prefer to only add units that will be actually used by someone. Mostly because the binary size is a lot bigger than I would like it to be for a library of this kind.

If you find any other units that would be useful to have Deca or other prefixes, let us know.
I would also encourage you to attempt a pull request to add the next unit or quantity, we are happy to assist and the wiki describes the steps involved. 👍

https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit
