### ISSUE TITLE
FeetInches.ToString as architectural format

### ISSUE THREAD

**Issue by lwestfall** [angularsen/UnitsNet#1075]
**Is your feature request related to a problem? Please describe.**
Not really

**Describe the solution you'd like**
It would be nice if FeetInches had a method to output a string in architectural format (including fractional inches). Using the example from below, it would output a string like `5' - 4 1/2"`.  

https://github.com/angularsen/UnitsNet/blob/ebd3275b84991f5d90113a03fb569cddd655c86e/UnitsNet/CustomCode/Quantities/Length.extra.cs#L235

**Describe alternatives you've considered**
An extension method works fine, and I'm happy to do this if it's not desired in this codebase but figured there may be others wishing for similar functionality.

**Additional context**
This is a pretty common notation in the US in certain contexts. I'm not sure if (the few) other cultures that use feet and inches have a different architectural format, so not sure how CultureInfo might play a role if any.

Related issue (never implemented AFIAK) #676. This would have to be implemented at the same time, so another thing to consider is how to deal with the fractional precision for rounding. Maybe via an argument, like an integer for the denominator?

I can contribute if this is wanted. I'm assuming we wouldn't want to override `ToString()` or any of it's overloads since that's already established. Maybe it'd be like `ToArchitecturalString(int fractionDenom)` ?

**Comment by angularsen** [comment]
Hi, adding an `ToArchitecturalString()` seems reasonable to me. 

As for rounding to a denominator, I assume you want to round 0.5 to the lowest form 1/2 instead of 2/4 if `4` was given as the denominator.

These seem relevant:
https://stackoverflow.com/questions/502021/how-do-i-round-a-decimal-to-a-specific-fraction-in-c
https://www.geeksforgeeks.org/reduce-the-fraction-to-its-lowest-form/

We'll figure it out, so please go ahead with a pull request and please provide a few unit test cases too. 😊

**Comment by lwestfall** [comment]
Agreed, I think the fraction should be reduced (after rounding to nearest fraction with precision to the given denominator).

I've already written this as an extension method so should be easy to bring it into this project, I'll include unit tests!
