### ISSUE TITLE
Add unit: PowerUnit.MegaBritishThermalUnitPerHour

### ISSUE THREAD

**Issue by DanielBuchberger** [angularsen/UnitsNet#1081]
Hi,
I would highly appreciate it if the unit **MegaBritishThermalUnitPerHour** could be added as **PowerUnit**. There is already **PowerUnit.KilobritishThermalUnitPerHour**, but in order to use UnitsNet for a project i would need that additional unit.

Let me know, if this unit is to exotic for you or if it makes sense to add it.

Greetings,
Daniel

**Comment by angularsen** [comment]
Hi, this unit sounds useful enough. Would you be willing to attempt a pull request?

It should be a matter of editing the Power.json to add a new prefix `Mega` for the existing unit, running `generate-code.bat` and adding a test case for the new unit (it will give a compile error about a missing property in the test code).

https://github.com/angularsen/UnitsNet/blob/master/Common/UnitDefinitions/Power.json#L86-L97

Detailed steps here:
https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit

I'm happy to assist.

**Comment by DanielBuchberger** [comment]
Hi,
First of all, thank you for the instructions and your time. I tried to follow them along with the instructions from the wiki. I think everything worked fined up to [5. Run tests](https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit#5-run-tests). Somehow I am not able to compile it in order to run the tests. If I run `build.bat`

```
 ...\UnitsNet\Build\build.ps1 : Failed to build.
System.Management.Automation.ParameterBindingValidationException: Das Argument kann nicht an den Parameter "Path" gebunden werden, da es NULL ist.
   bei System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   bei System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   bei System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   bei System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)' ]
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,build.ps1
```

Sorry for the German error message, it more or less translates to: "The argument cannot be bound to the Parameter "Path", because it is NULL".

I created a branch on my [forked repo](https://github.com/DanielBuchberger/UnitsNet/tree/MegaBritishThermalUnitPerHour).

Strangely, after running `generate-code.bat` an additional length unit seemed to be added (DataMile), I did not specify this one. Shall I revert those changes in the generated code?


Greetings and Thanks a lot!
Daniel

**Comment by angularsen** [comment]
I haven't seen this particular error before, not sure what is going on. 

The easiest is to open the solution in Visual Studio or Rider and build and run tests from there. The main point of step 5 is to ensure everything builds and tests are green before asking for review on the pull request.

If you still want to try to get the build scripts running, you may want to try downloading the latest PowerShell 7 and run `.\build.ps1` from that. Note that Windows bundles an older Powershell 5 named `powershell.exe`, but the newer versions are named `pwsh.exe`. 

You also need Visual Studio 2019 or later for it to find `vswhere.exe` and to locate `msbuild.exe`.

As for `DataMile`, you can merge in latest `master` from the main repo to your fork's branch. 

I just pushed a fix, because the generated code did not have all the latest pieces. This sometimes with parallel pull requests being merged.

**Comment by DanielBuchberger** [comment]
I tried it again from scratch, but without success. I am using Visual Studio 2022 and Powershell 7.2.3.
Do you mind if I create a PR without the tests working at my machine?

**Comment by angularsen** [comment]
Yes no problem, the PR will run the tests so you will see if it works there. The build agent is a bit slow though, may take 10-20 minutes to build the PR.
