### ISSUE TITLE
Update documentation on custom units

### ISSUE THREAD

**Issue by Brunni** [angularsen/UnitsNet#1132]
The documentation here is outdated. Some of the method parameters are deprecated:
https://github.com/angularsen/UnitsNet/wiki/Extending-with-Custom-Units

Also it is not really clear, if it makes more sense to implement IQuantity<T> instead of IQuantity.

Would it be possible to use the generator also for custom units?

**Comment by angularsen** [comment]
Yes that part of the wiki needs some love. Extensibility is still a bit work in progress, and the least mature part of the library. Generally we are going away from enums and towards string based values in v5 (#982 ), which helps a bit.

I believe the wiki is editable by anyone, so please just add your suggested changes to it.

> if it makes more sense to implement IQuantity instead of IQuantity.

Typo here maybe? IQuantity instead of..?
