### ISSUE TITLE
Power Ratio to Carrier Signal in decibels (dBc)

### ISSUE THREAD

**Issue by DaveJarvis** [angularsen/UnitsNet#1186]
We'd like to represent the power ratio of a signal to a carrier signal, expressed in decibels. If the power ratio is positive, then the relative signal strength is greater than the carrier signal strength. If the power ratio is negative, then the relative signal strength is less than carrier signal strength.

At the time of writing, this unit is not included in the UnitsNet library. If it is added in the future, we can remove a class from our code base. See https://en.wikipedia.org/wiki/DBc.

**Comment by angularsen** [comment]
Hi, I'm not familiar with this quantity. From skimming the wiki, it seems related to telecommunication and I have a sense that it might be too narrow/little used to include in the main library. We try to avoid too domain specific quantities to prevent bloat and binary size.

From the checklist [in the wiki](https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit#a-quantity-is-a-good-fit-to-add-if-it):

- What would the quantity name be, `PowerRatioToCarrier` ?
- Are there multiple units to represent this measurement and to convert between? Which?
- Can you convert from this quantity to other quantities? Other quantities with decibel units are `Level`, `PowerRatio` and `AmplitudeRatio`. https://github.com/angularsen/UnitsNet/search?l=JSON&q=decibel
- Are there domains besides tele communications where this is useful?

**Comment by angularsen** [comment]
Thank you for detailed background. Since this is a single-unit quantity, with no interaction with other quantities and with a narrow domain, I think this falls outside the scope for the main library.
Sorry!

You are probably better off creating your own quantity for this scenario.

You could implement `IQuantity` and plug it in as a custom unit, but I don't think you gain very much from that since it only has a single unit. Custom units is also a bit experimental and not very well supported yet.

https://github.com/angularsen/UnitsNet/wiki/Extending-with-Custom-Units#key-benefits
