### ISSUE TITLE
Was IQuantity.Value's return type intended to change to QuantityValue at v5?

### ISSUE THREAD

**Issue by tmilnthorp** [angularsen/UnitsNet#1205]
At v5 ```IQuantity.Value``` now returns a ```QuantityValue``` type rather than double. Was this intended? It's a bit of an obscure change since ```IQuantity.Value``` is implemented explicitly, so only seen when you have a left-hand side type of ```IQuantity```.

We have hundreds of places where we pass ```IQuantity.Value``` to an internal double method, and upgrading to v5 would require a cast to double on each one. 

Changing it back to double does not break any tests FWIW.

**Comment by angularsen** [comment]
It was introduced here, to better support decimal quantities.
#1074

Previously, double was always returned, also for decimal quantities.

Implicit cast from `QuantityValue` to `double` was explicitly left out to force the consumer to accept the (possible) conversion from decimal to double, since you don't really know from `IQuantity` alone. We have `IDecimalQuantity`, we could have had `IDoubleQuantity` I guess, but the whole double/decimal design is already kind of smelly.

This may all be moot if we indeed remove decimal altogether, as discussed in https://github.com/angularsen/UnitsNet/issues/1194#issuecomment-1423092652

**Comment by tmilnthorp** [comment]
Fair enough. Code incoming :)

**Comment by angularsen** [comment]
![waiting eating chips](https://media.giphy.com/media/3o6Zt3KFoI4XUfWmZ2/giphy.gif)

**Comment by tmilnthorp** [comment]
I present #1207
