### ISSUE TITLE
Bad conversion from base unit 0.1 (example: deciliter to liter) for decimal number.

### ISSUE THREAD

**Issue by tejouji** [angularsen/UnitsNet#1355]
**Describe the bug**
Whenever attempting to convert a decimal number to a unit with a base of 0.1, such as converting from deciliters to liters or decimeters to meters, the obtained result after the decimal point is on the order of 1e-17. 
Is it always necessary to round the result for conversions involving a base unit of 0.1?

**UT**
 UnitsNet 5.5.0 
 porject .NET 6.0 
 
![TU](https://github.com/angularsen/UnitsNet/assets/8770823/5a19a96a-2966-4e64-aae5-9bac7f21624c)

**Comment by angularsen** [comment]
This is due to floating point precision and using `double` value type internally.
Generally, when using `double` or `float`, you always need to handle precision errors, even if the calculation looks dead simple. There are many examples of simple numbers or simple calculations that these number types simply can't accurately represent.

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/floating-point-numeric-types
