### ISSUE TITLE
NuGets license: MIT instead of MIT-0

### ISSUE THREAD

**Issue by rc1cent** [angularsen/UnitsNet#1379]
The declared license for the nugets is MIT, but the license in the sources is MIT-0.
I see in the issues history that there were some problems with releasing the nugets with the MIT-0 license. There was even a try to use the MIT-0 license again, but not successful. It was quite a long time ago :).
Could you check if the MIT-0 license can be used now in the nugets? If so, then could you set this license? It would be great to have the correct license defined in the nugets for legal purposes, i.e. the list of used open source components :).

**Comment by angularsen** [comment]
Hi and thanks for checking in on this. 

I gave it a try and sucessfully pushed a new v6 pre-release version that targets MIT-0 license. It seems they finally added support for it.

https://www.nuget.org/packages/UnitsNet/6.0.0-pre005

I'll give it a little bit of time, but unless I find anything surprising I'll probably do the same for v5, since v6 is still not stable.
