### ISSUE TITLE
Electric Conductance per area quantity

### ISSUE THREAD

**Issue by bc913** [angularsen/UnitsNet#1398]
**Is your feature request related to a problem? Please describe.**
Electric conductance is already available in UnitsNet. However, we'd also need a definition of Electric Conductance per area quantity on a given surface to be able to define a local behavior during a physical phenomenon i.e. contact.  

**Describe the solution you'd like**
Implementation of ElectricConductancePerArea quantity.

**Additional context**
Ansys Workbench contact definition has a setting named "Electric Conductance" but w/ "S/m^2"

**Comment by bc913** [comment]
#1399

**Comment by angularsen** [comment]
I am a little hesitant to add this, it feels too domain specific and I can't find much on this particular quantity on Google. UnitsNet already has S, and google returns some stuff on S/m, but not much on S/m^2.

Not saying it is not used, but UnitsNet is trying to balance adding only the most widely used quantities to not bloat the library.

Thoughts @lipchev ?

**Comment by lipchev** [comment]
Same here, @bc913 are you sure you're not misinterpreting the Ansys Workbench parameter? We've already got the `ElectricConductance` (M^-1 L^-2 T^3 I^2) as well as the `ElectricConductivity` (M^-1 L^-3 T^3 I^2). 
I understand [these examples](https://www.electronics-tutorials.ws/resistor/resistivity.html)- and if I try to imagine your scenario would probably require a value measured `per length` (so that we get to divide the `L` in (L/RA) - such that we get something like 0.5 MS/m^2 for the last example. 

However, since I cannot find any examples / wiki-page for this (perhaps you could provide some?)- I also think that this is too niche (especially if all you need is to be able to substitute just that one division).

On a side note, I was thinking that we should probably try to invest some effort in implementing a template for creating a `composite quantity` - there have been many requests lately about adding `something per something-else` (representing existing quantities).

**Comment by bc913** [comment]
@angularsen @lipchev Sorry for the late response. Our initial attempt was to implement a custom (internal) quantity and unit. However, as the requirements are expanding, the implementation gets bloated and the final state gets closer to as if the feature was implemented using "GenerateCode". 

After some discussions and research, there is not much resource about this phenomena as you've pointed out. I understand and agree with you guys closing this.

**Comment by angularsen** [comment]
Thanks for reporting back 👍
