### ISSUE TITLE
Request: MolarEnergy

### ISSUE THREAD

**Issue by ferittuncer** [angularsen/UnitsNet#301]
We are modelling entropy and enthalpy in a scientific software project. Scientific papers we use, refer to molar based measurements such as `Joule per Mole` and `Joule per Mole per Kelvin`.

We couldn't find a good way to implement this using the library as-is. So we are willing to implement and contribute to the library but we thought it would be better if we discuss first.

Perhaps we can introduce a quantity type called MolarEnergy for it. What are your thoughts?

**Comment by eriove** [comment]
It seems to me like the best approach would be to add the quantities corresponding to J/mole and J/mole/K and operator overloads so that you can create them from the appropriate other quantities (such as Amount of substance, Energy and Temperature).

See [this](https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit) page for a description on how to add new quantities.

**Comment by ferittuncer** [comment]
We started to work on a quantity called `MolarEnergy` having a unit `Joule per Mole`.
