### ISSUE TITLE
Why does Power has "BaseType": "decimal"?

### ISSUE THREAD

**Issue by ferittuncer** [angularsen/UnitsNet#318]
Why does Power has `"BaseType": "decimal"`? I didn't see this in other quantities. Is it intentional?

**Comment by angularsen** [comment]
Yes, `Power` and `Information` are the only quantities with `decimal`. The reason is that they have the widest span of unit ... dimensions? Basically they represent very small and very large values, so it was hard to get the tests passing (with the default of 1e-5 precision error). Also, Information is by nature an integer value (N bits) so it made sense to not make it double as to avoid icky rounding errors, but I don't know if it really achieved that since all the `From()` methods still take `double` inputs.

We'll revisit this when we decide what to do with `double` vs `decimal` in #285.
