### ISSUE TITLE
Add more Flow units

### ISSUE THREAD

**Issue by gojanpaolo** [angularsen/UnitsNet#360]
CubicMeterPerMinute
CubicFootPerMinute
CubicYardPerSecond
CubicYardPerMinute
CubicYardPerHour
UsGallonsPerSecond
UsGallonsPerHour

**Comment by gojanpaolo** [comment]
I noticed that some of the unit definitions SingularName are not actually singular. Should I change those while at it?

      "SingularName": "LitersPerMinute",
      "PluralName": "LitersPerMinute",

      "SingularName": "UsGallonsPerMinute",
      "PluralName": "UsGallonsPerMinute",

      "SingularName": "OilBarrelsPerDay",
      "PluralName": "OilBarrelsPerDay",

**Comment by angularsen** [comment]
Hm, we should change this but that would be a breaking change and I don't see a good way to add new units and obsolete these as we have with other wrong namings in the past, since we would get name conflicts. I think we should add this to the wishlist issue (please locate it) and change this on the next major version bump?

**Comment by angularsen** [comment]
A bit busy these days, will try to find time this weekend if no one else picks up the review before then.
