### ISSUE TITLE
UnitsNet.Serialization v1.2.2 is not compatible with UnitsNet >= v3.92

### ISSUE THREAD

**Issue by gojanpaolo** [angularsen/UnitsNet#416]
@angularsen The current released UnitsNet.Serialization v1.2.2 is not compatible with UnitsNet v3.92 and up.
Releasing the latest build should fix the issue.

**Comment by angularsen** [comment]
Wat? Doh, of course!

#389 
> There should be no breaking changes in neither main lib nor JSON serialization.

I am a lying bastard, that's what happened :-)
All my tests were using the latest UnitsNet code, so I did not actually test with the old JSON code.
Oh well, I think I can live with this compromise instead of trying to make it truly backwards compatible - because that sounds really painful and maybe not even possible without reverting the whole thing.

**Comment by angularsen** [comment]
Json nuget 1.3.0 is out.

**Comment by gojanpaolo** [comment]
Awesome! Thank you. closing this issue. :)

**Comment by gojanpaolo** [comment]
I think it's fine even without backwards compatibility. But is it possible to also run the unit tests on the latest released version of both libraries? This would help catch this kind of issue early.

**Comment by angularsen** [comment]
Yes that's a good idea, the json tests could possibly run against two UnitsNet dlls. I'm not exactly sure how, but it seems you can side-load two versions of a dll and call them separately:

https://stackoverflow.com/questions/42715564/using-2-different-versions-of-the-same-dll
https://devnet.kentico.com/articles/referencing-multiple-versions-of-the-same-assembly-in-a-single-application
https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/codebase-element

**Comment by angularsen** [comment]
Created issue https://github.com/angularsen/UnitsNet/issues/417
