### ISSUE TITLE
Please add a centiampere

### ISSUE THREAD

**Issue by lim8603** [angularsen/UnitsNet#449]
Please add centiampere to ElectricCurrent. ^^

**Comment by angularsen** [comment]
Hi, we encourage our users to add the units they are missing themselves so that it's easier to add more units later. We have a very detailed step-by-step process here: https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit

When you have done it once, it is in fact very easy to do and basically only a matter of editing a .JSON file and running a powershell script to regenerate the code. Then submit a [pull request](https://help.github.com/articles/creating-a-pull-request/) and we will merge it in.

Would you please give it a try? 

We are happy to assist if you face any challenges, in the pull request or in the [chat](https://gitter.im/UnitsNet/Lobby).

**Comment by angularsen** [comment]
Add "Centi" to the "Prefixes" array here: https://github.com/angularsen/UnitsNet/blob/master/UnitsNet/UnitDefinitions/ElectricCurrent.json
