### ISSUE TITLE
Add netstandard 2.0 target

### ISSUE THREAD

**Issue by angularsen** [angularsen/UnitsNet#477]
To avoid all the dependencies that netstandard 1.0 brings with it.

We should also consider removing 1.0, since that no longer brings much value to the table I think, except for older versions of Xamarin and similar. 

People on NET 4.0-4.6.1 will simply use 4.0 dll and 4.6.2 and up will then use netstandard 2.0 dll.

Inspired by this tweet:
https://twitter.com/onovotny/status/1040053354465030144?s=19

**Comment by angularsen** [comment]
Will be fixed in v4.

**Comment by tmilnthorp** [comment]
So I just noticed that all of our C++/Cli projects complain with the following warning:

warning C4691: 'System::Nullable': type referenced was expected in unreferenced assembly 'netstandard', type defined in current translation unit used instead

Even though we are targeting .NET 4.6.2, it seems netstandard has issues. Everything does seem to work though, just the nagging compiler errors. I wonder if we should add a .NET 4.6.2 target for C++/Cli use cases, since netstandard seems to be unsupported.

**Comment by angularsen** [comment]
@tmilnthorp Have you looked through these? 
A bunch of different suggestions from this comment and down: https://github.com/dotnet/standard/issues/542#issuecomment-440589385

Is it an option to reference the existing .NET 4.0 build of UnitsNet?

**Comment by tmilnthorp** [comment]
I can't do a lot of the suggestions due to C++/Cli having a native target Framework, and also doesn't support package references.

I did target the 4.0 version and everything worked. I just worry a bit about hidden gotchas 😟

**Comment by angularsen** [comment]
I see, is it an option to try it out for a while and see if any bugs arise?

I'm a bit hesitant to add another seemingly redundant build target for a compile warning in a tooling I had not even heard about until today, but we can absolutely do it if it adds value.

**Comment by tmilnthorp** [comment]
That works! I'll see how it goes
