### ISSUE TITLE
Binary Serialization

### ISSUE THREAD

**Issue by RickDaniel** [angularsen/UnitsNet#564]
What are the barriers to binary serialization using the built in .Net Framework serializer? UnitsNet is exceptionally useful in our project. While adopting, I discovered that we can't use binary serialization with it. We have a deep object graph with heavy use of references among a complex structure as well as lots of events and delegates. Historically binary serialization has been important for us.

**Comment by RickDaniel** [comment]
I am happy to attempt some modification, but simply wondered what I should watch out for.

**Comment by angularsen** [comment]
Hi, 

We're only missing the `[Serializable]` attribute on quantity types like `Length`.

I think the biggest hurdles are:

1. BinaryFormatter is notoriously easy to break backwards compatibility (it requires exact namespace and class name to be preserved, or add mapping to handle changes). I would advocate using protobuf-net, ZeroFormatter, DataContractSerializer or any of the other contract-based binary formats if you can. It really is much more robust for future changes.
2. Serializing `Length` is not a good idea, it WILL receive breaking changes at some point. You should instead serialize a data contract type that is designed to be stable, similar to `UnitValue` used by `UnitsNetJsonConverter` for JSON.net serialization. 
3. We haven't invested any energy on making this work, simply because many of us have not needed this feature, but if you want to come up with a design for how we can support binary and xml serializers  and still make it robust for future changes, I'm happy to discuss the design and accept a PR on it once we have the design nailed.

I gave it a quick try just now, added `[Serializable]` to `Length` type and added a new test:

```c#
        [Fact]
        public void BinarySerializerTest()
        {
            using (var stream = new MemoryStream())
            {
                var bf = new BinaryFormatter();
                bf.Serialize(stream, Length.FromCentimeters(100));

                stream.Position = 0;
                Length readLength = (Length)bf.Deserialize(stream);
                Assert.Equal(100, readLength.Value);
                Assert.Equal(LengthUnit.Centimeter, readLength.Unit);
            }
        }
```

It serializes just fine.

For your reference, here are some previous discussions:
https://github.com/angularsen/UnitsNet/issues?page=2&q=serialization&utf8=%E2%9C%93

In particular these:
https://github.com/angularsen/UnitsNet/issues/92#issuecomment-126601967
https://github.com/angularsen/UnitsNet/pull/96

**Comment by RickDaniel** [comment]
Thank you! That was a very thorough and knowledgeable answer! And fast! I think I understand everything you mentioned, including the perils of BinaryFormatter. I'll explore the ideas you mentioned carefully.

**Comment by angularsen** [comment]
Great! Happy to help :-)
