### ISSUE TITLE
Diabetes related units

### ISSUE THREAD

**Issue by kgrosvenor** [angularsen/UnitsNet#690]
Would be nice to have units like DiabeticUnits.fromMgdl(num).toMmol()

the formula for this is 

mg/dL = mmol/L * 18
mmol/L = mg/dL / 18

**Comment by lipchev** [comment]
Hello,
Looking at the wiki for [Blood sugar level](https://en.wikipedia.org/wiki/Blood_sugar_level) it seems to me that all unit types are already implemented:

1. The international standard way of measuring blood glucose levels is in terms of a [molar concentration](https://github.com/angularsen/UnitsNet/blob/master/UnitsNet/GeneratedCode/Quantities/Molarity.g.cs), measured in mmol/L (millimoles per litre; or millimolar, abbreviated mM)
2. In the United States, Germany and other countries [mass concentration](https://github.com/angularsen/UnitsNet/blob/master/UnitsNet/GeneratedCode/Quantities/MassConcentration.g.cs) is measured in mg/dL (milligrams per decilitre).
3. Since the [molecular weight](https://github.com/angularsen/UnitsNet/blob/master/UnitsNet/GeneratedCode/Quantities/MolarMass.g.cs) of glucose C6H12O6 is 180, the difference between the two units is a factor of 18, so that 1 mmol/L of glucose is equivalent to 18 mg/dL

So if you had the constant defined somewhere in your domain (I don't think that introducing such constants is within the current scope of this project), you could easily convert from Molar to Mass Concentration using the helper methods:

- [MassConcentratino.extra](https://github.com/angularsen/UnitsNet/blob/master/UnitsNet/CustomCode/Quantities/MassConcentration.extra.cs)
 
- [Molarity.extra](https://github.com/angularsen/UnitsNet/blob/master/UnitsNet/CustomCode/Quantities/Molarity.extra.cs)

- you can also have a look at the conversion test [here](https://github.com/angularsen/UnitsNet/blob/d85c011f31a64d77eccd5874d2e5d9a0a859c169/UnitsNet.Tests/CustomCode/MassConcentrationTests.cs#L79)

**Comment by kgrosvenor** [comment]
@lipchev Thank you, i'll take a look & thank you for the swift and informative response i appreciate it

**Comment by angularsen** [comment]
Thanks @lipchev, awesome answer!

**Comment by angularsen** [comment]
Closing this for now, reopen if you want to discuss further.
