### ISSUE TITLE
 No units were found for the given UnitSystem: Convert non-base units to SI

### ISSUE THREAD

**Issue by SGStino** [angularsen/UnitsNet#700]
**Is your feature request related to a problem? Please describe.**
Converting L/h to SI results in "No units were found for the given UnitSystem"

**Describe the solution you'd like**
I'd love to see the values as m³/s in the SI case.
 
The use-case is a .NET tool that collects data from various sources in various units (including some weird ones like hL/min, which causes another problem for the moment) and outputs them on a single channel in SI unit by convention.
This channel is used by multiple tools written in multiple languages, hence the SI convention.

Currently we have to remove the Unit from the value and apply a custom scale factor that we have to set it manually (=little more error prone)

this means:
`output = input * 4.41631375E-05`
 instead of 
 `output = VolumeFlow.FromOilBarrelsPerHour(input).As(UnitSystem.SI)`

**Comment by angularsen** [comment]
Thanks for describing the usecase. The UnitSystem concept is still quite new and we have not yet mapped all the units that should be the result of converting a quantity to SI base units. We are also debating a redesign of the system, since it can't easily be used to represent other units than SI - such as CGS, FPS, British Engineering units and so on.

There are some discussions in #651 and #630 on a possible redesign.

However, I believe your scenario can be implemented by adding `BaseUnits` to the cubic meters per second unit in `VolumeFlow.json`, such that `.As(UnitSystem.SI)` will convert to that unit. Remember to run `generate-code.bat` after changing .json files.

If you are willing to do a pull request, I'm happy to assist.
