### ISSUE TITLE
New release of UnitsNet.Serialization.JsonNet

### ISSUE THREAD

**Issue by Michael-F-Bryan** [angularsen/UnitsNet#718]
Are you able to generate a new release of `UnitsNet.Serialization.JsonNet`? The current version depends on ` Newtonsoft.Json >= 9.0.1 `, but I'm encountering DLL hell because most other libraries use the more recent `Newtonsoft.Json >= 12.0.0`.

It [looks](https://github.com/angularsen/UnitsNet/blob/a550f1b80bdebbddfdd4bcbf6db183bf3c3093cc/UnitsNet.Serialization.JsonNet/UnitsNet.Serialization.JsonNet.csproj#L46) like the version has already been bumped, so this should just be a case of uploading the latest code to nuget.

**Comment by angularsen** [comment]
Interesting conundrum. It seems I recently upgraded it as part of upgrading all nugets and I didn't notice at the time I had also touched the JSON library.

We could absolutely publish an upgrade, I'm just a bit unsure if we need to bump the major version of the JSON library from 4.0 to 5.0 in order to signify this possible breaking change or if it's fine to go with 4.1? The downside is that the major version is no longer in sync with the major version of UnitsNet 4.x, which it depends on.

What do you think @tmilnthorp @lipchev ?

**Comment by Michael-F-Bryan** [comment]
I ended up working around the version differences locally using a combination of binding redirects and a couple other tricks, so a new release may no longer be needed.

**Comment by angularsen** [comment]
This will always be a problem for nugets that have their own depedencies and the consumer has to resort to binding redirects. It's a mess, but besides bundling json.net as a private dependency I don't see a better solution than to try to keep its dependency version up to date. Just not sure about the versioning scheme yet.

Come to think of it, maybe libraries like this _should_ bundle its JSON implementation as a private dependency to avoid this problem to begin with. You get a slightly bigger binary size, but that's about the only downside I can think of. Thoughts?

**Comment by dschuermans** [comment]
@angularsen  would this explain why I can't use the UnitsNetJsonConverter now that I'm upgrading to UnitsNet 4.42.0 and UnitsNet.Serialization.JsonNet 4.0?

Up until now I had a copy of the UnitsNetJsonConverter that contained the fixes for Array seralization etc that I recently merged

I get the following:

![image](https://user-images.githubusercontent.com/6634696/71892760-15204a00-314a-11ea-98b8-ae632ed8bdb9.png)

and we're using Json.NET 11.0.4

**Comment by dschuermans** [comment]
> @angularsen would this explain why I can't use the UnitsNetJsonConverter now that I'm upgrading to UnitsNet 4.42.0 and UnitsNet.Serialization.JsonNet 4.0?
> 
> Up until now I had a copy of the UnitsNetJsonConverter that contained the fixes for Array seralization etc that I recently merged
> 
> I get the following:
> 
> ![image](https://user-images.githubusercontent.com/6634696/71892760-15204a00-314a-11ea-98b8-ae632ed8bdb9.png)
> 
> and we're using Json.NET 11.0.4

Upgrading to Newtonsoft.Json 12.0.3 solved this particular issue FYI.

I think if you were to use Newtonsoft.Json 9.* in the UnitsNet.Serialization.JsonNet project, any projects using a higher version of Newtonsoft.Json should still be able to use the package?
Unless of course there has been a breaking change for JsonConverter implementations since 12.*

**Comment by angularsen** [comment]
As pointed out in #731, the array support was just released in UnitsNet.Serialization.JsonNet 4.1.1.

@Michael-F-Bryan This release also includes the upgrade to JSON.NET 12.0.3. Hopefully it won't cause too many problems so I treated it as a minor version bump.
