### ISSUE TITLE
Incorrect ThermalResistance conversion between SquareMeterKelvinPerKilowatt and SquareMeterDegreeCelsiusPerWatt

### ISSUE THREAD

**Issue by mheyse** [angularsen/UnitsNet#720]
**Describe the bug**
The conversion factor in Common/UnitDefinitions/ThermalResistance.json between SquareMeterKelvinPerKilowatt and SquareMeterDegreeCelsiusPerWatt is defined as 1000.088056074108 - but as a temperature difference of 1K is exactly the same as a temperature difference of 1°C and 1kW is 1000W the conversion factor should be exactly 1000 instead.

**To Reproduce**
var tr = ThermalResistance.FromSquareMeterKelvinsPerKilowatt(1000);
Console.WriteLine(tr.SquareMeterDegreesCelsiusPerWatt);
Output: 0.9999119516790815

**Expected behavior**
Expected output: 1

**Screenshots**
N.A.

**Additional context**
N.A.

**Comment by rgomez90** [comment]
I think this is a bug, and I can also see the conversion to `SquareCentimetersKelvinPerWatt` is also wrong.

@angularsen I can make a quick PR to fix this if you want

| Unit  | Symbol | Conversion  |
| ------------- | ------------- | ---------- |
| watt per square meter per kelvin | W/(m2 • K) | 1 W/(m2 • K) |  
| kilowatt per square meter per kelvin | kW/(m2 • K) | 1e+03 W/(m2 • K) |  
| watt per square centimeter per kelvin | W/(cm2 • K) | 1e-04 W/(m2 • K)

**Comment by rgomez90** [comment]
I've taken a look and the tests pass, because there is a tolerance factor of  `1e-5`.

But I don't know if there is a reason for the conversion factors not being plain 1000 or 1.

Maybe @angularsen can give some info why the factors are as they are.

If there is no reason I could make a quick PR to fix this.

The conversion table is




| unit name  |  symbol  |  SI equiv  |
| --------- | --------- | --------- |
| watt per square meter per kelvin | W/(m2 • K) | 1 W/(m2 • K) |
| kilowatt per square meter per kelvin | kW/(m2 • K) | 1e+03 W/(m2 • K) |
| watt per square centimeter per kelvin | W/(cm2 • K) | 1e-04 W/(m2 • K) |

**Comment by angularsen** [comment]
Hi guys, I don't know this domain of units but I agree with your reasoning. I can't see why these values were added in the first place. The change was added back in 2017-03-09.

A PR would be awesome, thanks!

**Comment by angularsen** [comment]
@rgomez90 Are you still interested in fixing this?

**Comment by ikijano** [comment]
I noticed that this issue wasn't fixed. I can create PR to fix this as this is near my domain and @rgomez90 reasoning is valid.

**Comment by angularsen** [comment]
Perfect, please do 👍 Let us know if you need any assistance.
