### ISSUE TITLE
Thermal resistance vs resistivity vs insulance

### ISSUE THREAD

**Issue by mheyse** [angularsen/UnitsNet#721]
**Is your feature request related to a problem? Please describe.**
Several different quantities related to heat flow resistance exist. According to Wikipedia (https://en.wikipedia.org/wiki/Thermal_resistance) they are named
* Thermal resistance [K/W]
* Thermal resistivity [K·m/W]
* Thermal insulance [m·m·K/W]

(Not a native English speaker, so I don't know if these terms are really correct).
So according to this Wikipedia article, UnitNet's quantity "ThermalResistance" (unit "m·m·K/W") should actually be named "ThermalInsulance".

My problem is that I want to add a quantity with unit K/W that should be named ThermalResistance according to Wikipedia but this name is already in use by the quantity with unit m·m·K/W.

**Describe the solution you'd like**
Finding a solution for naming the three quantities listed above. I think the cleanest solution would be renaming ThermalResistance to ThermalInsulance and adding the others but I guess this would be difficult as it breaks backwards compatibility.

**Comment by angularsen** [comment]
Thanks for reporting and describing so well.
I don't know this domain well myself, the ThermalResistance was added by @Hareeshs in 2017. Maybe he could comment on this?

Assuming you are correct about this, there are two ways I see:
1. Make a breaking change and rename it by adding a pull request to `release/v5` branch. There is no ETA on that release yet, but we did want to get it out sometime soon :tm:. Currently waiting on completing work around the new `UnitSystem` design. #563 
2. Add a copy of `ThermalResistance`, name it `ThermalInsulance` and mark the old one as `[Obsolete]` with a text explaining to use the new one. Add `ThermalResistance2` or a similar placeholder name, that we will rename in `v5`. At least it can be used until then.

**Comment by angularsen** [comment]
@mheyse Do you have any comments on my suggestions? Are you still interested in pursuing this and making a PR?

**Comment by ikijano** [comment]
I like to open this again as ThermalResistance base unit should be K/W instead of m2⋅K/W which is unit of Thermal insulance.
How could I can help with this? Definitely it would be braking change.

Personally have also needs for SpecificThermalResistance (K⋅m/W). I'm working with project where borehole equivalent thermal resistance (which have unit K⋅m/W) calculation is needed and I like to use UnitsNet in there.

**Comment by angularsen** [comment]
Hi, we have a v5 branch going on #982 .

Since it is a breaking change, I propose you make a pull request to that v5 branch instead, then when it's ready and done we can mark things as obsolete in v4. You can then use the prerelease nuget until v5 is fully merged, which is likely to take some time due to low momentum.
