### ISSUE TITLE
Add overloads to work with Ratio directly

### ISSUE THREAD

**Issue by bitbonk** [angularsen/UnitsNet#723]
Suppose you have a Ratio and and arbitrary other quantity:

```
var power = Power.FromWatts(42);
var correctionFactor = Ratio.FromPercent(50);
``` 

Currently it is not possible to do the following:

```
Power correctedPower = power * correctionFactor;
```

Instead I have to do the following: 

```
Power correctedPower = Power.FromWatts(power.Value * (decimal)correctionFactor.DecimalFractions);
```

This is not very discoverable and very tedious to use. I think it may also be error prone due to the fact that you sometimes have to cast between `double` and `decimal` where you could potentially could loose precision.

So I suggest that you add operator overloads to work with Ratio for all quantities.

**Comment by angularsen** [comment]
Hi, good suggestion. I can see how that brings some value. The one complication I see is that `Temperature` cannot have a multiplication overload, because 0 Celsius != 0 Fahrenheit != 0 Kelvins so multiplication requires a reference temperature (twice relative to what).

One way to go about this is to extend our JSON quantity definitions and code generator with a new field `"DisableRatioArithmetic": "false"` that defaults to `false`, then we set that to `true` for `Temperature` so that only the other quantities get the Ratio multiplication/division overloads.

If we do that, then I would argue that we should do the same for `double` and `decimal` multiplication/division. We can get away with only one instead of two extra method overloads by using the `QuantityValue` type, which has implicit casts from `double` and `decimal`.

Then finally we would need to remove the custom multiplication/division methods already added since these would now be generated.

Would you be interested in attempting a pull request on this? I'd be happy to assist.
