### ISSUE TITLE
Add several Force per length conversions

### ISSUE THREAD

**Issue by peterjamesnugent** [angularsen/UnitsNet#785]
**Is your feature request related to a problem? Please describe.**
Add a number of force per length unit conversions.

**Describe the solution you'd like**
See list below.

**Describe alternatives you've considered**
I could use a combination of conversions, so to go from N/m to kN/cm making use of the the force and length unit conversions. However, this can get quite convoluted and some quantities can be making two (moments) or three (pressure) conversions. It would be cleaner to have a single conversion.

**Additional context**
Force per length:
- NewtonPerCentimetre
- KilonewtonPerCentimetre (this comes by extension of the above)
- KilogramforcePerCentimetre
- KilogramforcePerMillimetre
- TonneforcePerMetre
- TonneforcePerCentimetre
- TonneforcePerMillimetre
- KilopoundforcePerInch

**Comment by angularsen** [comment]
Hi and thanks for describing.

At first glance, it seems you are mixing units from the metric and imperial systems. 
For instance, `Newton-foot`. I don't immediately find any relevant hits on google for this unit, so it does not seem like it is commonly used.

Could you please give an example where adding one of these units would help you?

**Comment by peterjamesnugent** [comment]
Yeah you're right, mixing Imperial and Metric units does not make sense. 

I am using a software that can set force units or length units independently, so you could get a scenario with imperial force and metric length. However, I cannot think of a practical application for that.

I have updated the issue for a few force per unit length conversions that are either Imperial or Metric. 

I have left out moment per unit length quantities such as kNcm/cm as the conversion is just for a force quantity, unless you think it's worthwhile including it?

**Comment by angularsen** [comment]
Makes sense. The remaining units look good to me.
1. Would you be willing to do a pull request? 

We really prefer that those who request the units add them, so we know they will be used and tested.

Step by step instructions are detailed in https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit.

2. Moment per length

> I have left out moment per unit length quantities such as kNcm/cm as the conversion is just for a force quantity, unless you think it's worthwhile including it?

As a rule of thumb, we only want to add units that someone will actually use. So if you would make use of this unit, then we can add it.

3. The naming convention in this library is `Meter` instead of `Metre`, just a heads up if you go ahead with the PR.

**Comment by peterjamesnugent** [comment]
Sure, I can take a look at that - I'll come back if I have any questions.

**Comment by angularsen** [comment]
Excellent, don't hesitate to ask 👍
