### ISSUE TITLE
Is it possible to add new Unit Humidity?

### ISSUE THREAD

**Issue by ilchdeveloper** [angularsen/UnitsNet#822]
[Humitidy.json.txt](https://github.com/angularsen/UnitsNet/files/5059739/Humitidy.json.txt)

Hello Andreas,

We liked your project and work. We want to use UnisNet library in a feature. I try to add the Humidity Unit pre your instructions - https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit. The codegen run well, but when I run build.bat I get a lot of errors:
![Capture](https://user-images.githubusercontent.com/20879796/89954250-bf8bae80-dbfe-11ea-9b87-d11486729473.PNG)

We don't use the VS 2019. Could you please give us the advice about how we can do it in our environment:  VS2017 and .Net Framework 4.7.1

Thank you!!!

**Comment by angularsen** [comment]
Hi, this project should build just fine on VS2017 (or even without Visual Studio at all).

I believe the only requirement is [.NET Core SDK 2.x](https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit#requirements).

You could also try creating a pull request and see if the automated build runs OK. But it's easier to experiment locally of course.

**Comment by angularsen** [comment]
I see you added the PR already, I assume you figured it out. Closing this issue.

**Comment by krwq** [comment]
@angularsen I'd also prefer to have this unit, please reconsider (although I would call it RelativeHumidity).

The reasoning is that we'd like to have strongly typed units in https://github.com/dotnet/iot which have lots of benefits: i.e. our [WeatherHelper](https://github.com/dotnet/iot/blob/master/src/devices/Common/Iot/Device/Common/WeatherHelper.cs) could be implemented partially as extension methods. We could also use the strongly typed unit also to generate the code but since sensors returning relative humidity return the ration instead of RelativeHumidity that makes it a bit harder.

I understand if you push back on that (in such case we'd likely just add similar unit in our repo but I think this repo is a good place to have them all in one place rather than spread across the ecosystem)

**Comment by angularsen** [comment]
@krwq Thanks for chiming in. It helps to have multiple points of view. If several people ask for a quantity, then I think that helps justify adding it.

There is a PR #824 to add quantity `Humidity` with unit `Percent` `%Rh`. Does that cover your needs, or would you need any modifications?

**Comment by krwq** [comment]
@angularsen yes, looks good! Additional fraction unit (0..1) for humidity would be useful as well but percent is sufficient to cover most of the needs.

**Comment by angularsen** [comment]
Great, I will reopen #824 and continue the conversation there.
