### ISSUE TITLE
Add new Unit for Mass Quantity Type

### ISSUE THREAD

**Issue by givemysun** [angularsen/UnitsNet#852]
**Is your feature request related to a problem? Please describe.**
We want to extend the MassUnit enum and being able to differentiate Metric Tons (air) vs Metric Tons (vac). 
How can we add new Unit for Mass Quantity Type? 
Can we add it at runtime?

**Describe the solution you'd like**
Being able to add new Unit for each Quantity Type at runtime or with Convention. Avoiding to create a branch, modify the json file and running the code generator.  Is it possible?

**Comment by angularsen** [comment]
Hi, please take a look at https://github.com/angularsen/UnitsNet/wiki/Extending-with-Custom-Units for how to add custom units and quantities at runtime. This gives you Parse, ToString and conversions between units.

If you wish to add the unit to the main library nuget for others to consume, then see https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit. However, it seems to me these units are perhaps a little too domain specific to include in the main library, but we're open to discuss if they are widely used and would benefit many people.

**Comment by givemysun** [comment]
Hi Andreas! 
Thank you very much for your answer. 

I read all the docks but still can't envision how to do it. 
Creating a Custom Mass Structs and copy and past all in order to extend seams quite strange.
Unfortunately 
1) I can't create another partial Class to extend since I did not share the same namespace. 
2) I can't Inherit from a struct like this: CustomMass : Mass

So my question is, how did you see the ability to extend (Being open for extension) your Library for developers? 
It seams that I'll be forced to this approach: https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit. 
Right?

**Comment by angularsen** [comment]
Hi, first I would like to point out that extending with custom quantities and custom units is probably the least mature part of this library. It kind of works, but it has some rough edges and could probably use some improvements.

I assume you read the example of the [sample quantity HowMuch](https://github.com/angularsen/UnitsNet/wiki/Extending-with-Custom-Units#sample-quantity) on `public struct HowMuch : IQuantity`.

As you point out, you can't inherit from `Mass` unfortunately since it is a `struct`. 

You can create a wrapper type `MyCustomMass` that has a `private readonly Mass _mass;` field that holds the actual mass, then you can implement your own methods like `ToUnit(MyCustomMassUnit)` and `ToUnit(MassUnit)` and either convert with your own code or forward to `_mass` where appropriate.

If you want to be able to pass your `CustomMass` around as if it was a `Mass`, then you can implement [implicit conversion](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/user-defined-conversion-operators) for something like 

```c#
MyCustomMass customMass = MyCustomMass.FromMyCustomUnit(1);
Mass mass = myCustomMass;
```

Does that help.
