### ISSUE TITLE
Removing the Undefined unit

### ISSUE THREAD

**Issue by lipchev** [angularsen/UnitsNet#983]
1. Replace with non-nullable value (constructing with BaseUnit by default)
`private readonly MassUnit? _unit;`
2. Remove all the guard checks:
`            if(unit == MassUnit.Undefined)
              throw new ArgumentException("The quantity can not be created with an undefined unit.", nameof(unit));`

**Comment by angularsen** [comment]
Fixed in v5

**Comment by angularsen** [comment]
@lipchev DefaultDataContractJsonSerializerTests is failing on removing the Undefined unit.

Basically, there is now an off-by-1 error in some tests.

However, I realize now that it is a really bad idea to serialize the unit integer value, because units are added alphabetically to the unit enum type, so it is in fact very likely that a unit will get a different integer value over time.

What do you think we should do with this serializer?

![image](https://user-images.githubusercontent.com/787816/141662550-7094a479-422d-4da4-a5b1-9caa699aabbb.png)

**Comment by angularsen** [comment]
See latest release/v5 branch.

**Comment by lipchev** [comment]
Yes, that is the limitation of the **default** behavior- you _have_ to keep your versions in sync. Alternatively, one can create a surrogate (like we did earlier) for the IQuantity or even globally for the [Enum type](https://canbilgin.wordpress.com/2012/06/07/how-to-serialize-an-enum-as-string-with-idatacontractsurrogate/). 

Unfortunately, this same limitation applies to the tests. It is a little inconvenient to have to change the expected-string every time a Mass/Information unit is added but at the time it felt better than something like `"{\"Value\":1.2,\"Unit\":\"{(int)MassUnit.Milligram}\"}"`.

**Comment by angularsen** [comment]
Gotcha. So, I guess we definitely need to provide a surrogate before we start advertising support for the default JSON contract serializer then?

**Comment by angularsen** [comment]
Right, but I'm thinking we shouldn't document DataContractJsonSerializer as being supported by Units.NET on the readme/wiki unless we also provide a surrogate that fixes the enum issue. People may then use it without thinking twice, and run into subtle serialization bugs in the future when we add more units.

Currently, only json.net is documented as supported:
https://github.com/angularsen/UnitsNet#serialization

I propose adding a new section covering Json/Xml data contract serializers and describing their current behavior and why the JSON one is not recommended due to this limitation. The XML one serializes enum name, doesn't it?

**Comment by lipchev** [comment]
> The XML one serializes enum name, doesn't it?

Yes it does.

> I propose adding a new section covering Json/Xml data contract serializers and describing their current behavior and why the JSON one is not recommended due to this limitation

I agree, although I'm not sure how I would group the serialization sub-sections:

- we could have them split as being `Out-of-the-box'  or part of a NuGet
- we could have them as XML, Json, Binary 
- they could be (further) split into `Recommended` and `Legacy`
- there could be a (simpler) version of the table I showed in #907 containing all options

**Comment by lipchev** [comment]
On the subject of the Undefined unit- it appears that with C#10 we can now have [parameterless-struct-constructors](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/parameterless-struct-constructors) - which in our case can default to ` : this(0, ConversionBaseUnit)`

**Comment by angularsen** [comment]
Right. I have been contemplating whether we could make the move to Record types for the target frameworks that support it. It would give us all the flexibility of classes and inheritance, while remaining immutable. However, for the small crowd of memory sensitive applications, struct is probably still preferred. So I guess

I don't expect to land this for v5, but the idea occurred to me that maybe there is a better middle-ground than class vs struct.

**Comment by angularsen** [comment]
Fixed the test cases in v5 branch by casting the expected units to int.
